import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AlimentoProvider from "@/contextApi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AlimentoProvider>
      <html lang="pt-br">
        <body>
          <div className={`
            flex flex-col justify-center items-center 
            h-screen w-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-zinc-400 to-[#0D736A]
            `}>
            {children}
          </div>
        </body>
      </html>
    </AlimentoProvider>
  )
}